### ISSUE TITLE
Testing linkability of linkable ring signatures

### ISSUE THREAD

**Issue by jchen86** [HarryR/solcrypto#5]
Hi @HarryR 

Thanks for your great work on the libraries!

I have a use case where I could potentially use linkable ring signatures: given a group of authorised users, I'd like each of them to be able to add an entry to a list without revealing who they are, but each of them can only add one entry - each user must not be able to add more than one entry (same or different).

I'm still trying to get my head around the concept and implementation - so apologies for any incorrect assumptions or terminologies. I have tried using [uasring.py](https://github.com/HarryR/solcrypto/blob/master/pysolcrypto/uaosring.py) to generate signatures, but I'm unsure how to test the linkability of two signatures.

My observation is that the return value of the [uaosring_sign](https://github.com/HarryR/solcrypto/blob/master/pysolcrypto/uaosring.py#L51) function "T" returns the same value when two messages are signed by the same party, but returns different results when the contents of the two messages are different. Is this "T" value used for testing linkability? If it is, is there a way to find out whether two different messages are signed using the same private key?

Thank you!

**Comment by HarryR** [comment]
>  Is this "T" value used for testing linkability?

 Yes, it is. If there's a ring of 10 public keys, each participant can sign the same message exactly once - they will all have unique `T` values, if they try to sign the message twice you can reject their signature for a duplicate `T` value for that message.

>  is there a way to find out whether two different messages are signed using the same private key?

It shouldn't be possible, because that would break the Decisional Diffie-Hellman (DDH) problem, and probably the ring signature too.

------

In your example there's a set of authorised public keys, and you want each of them to be able to add at most one entry each. In this case you would need the message to be 'Group of people A is adding to list B', so you'd hash all of the public keys and a GUID for the list together and use that as the message.

The problem though, is that the item they want to add to the list isn't authenticated, e.g. you just have a membership statement of 'I am one of A adding to list B', with the item as an unauthenticated parameter. An example of an attack is, Eve observes the blockchain mempool - when somebody submits an 'add to list' transaction she submits another one which re-plays their membership statement (their ring signature) but with a different vote. You can't allow votes to be changed after the fact either, otherwise anybody could re-play with different votes too.

So, this only works when the list is a binary signal, and the number of signatures indicate how many voted for (e.g. 1) - and however many didn't sign indicates how many voted against (e.g. abstaining from the vote = a no vote).

To authenticate the item they're adding to the list, they'd have to include that in the message, but then every signature would have different `T` values for every item, and you couldn't prevent people from voting twice.

------

There may be some algorithm using a combination of pairings and ring signatures, which allows you to authenticate an additional parameter while keeping the `T` value linkable to prevent double votes, but I'm not sure what that would be - but, if there is - it would make anonymous 'add to list' possible using ring signatures.

That would be some interesting research, and would make many interesting things viable.

**Comment by jchen86** [comment]
@HarryR Thanks for your quick response and amazing insights!

I feel that the solution you described might just work for us, assuming that the signatures are stored when an entry is added. 

Given that everyone in the group signs the same message like what you described, each of them will and only be able to create one unique trace "T". Let's assume that user sends a signature of this message, along with a arbitrary message in one single transaction. If we store this "T" value (e.g. on a smart contract) when an entry is added, and do a check every time another entry is added, then we should be able to reject future entries that comes with the same "T" value?

I'm not sure about the need to authenticate the item in this case. Do you see any problems with this?

**Comment by HarryR** [comment]
> where user first submits a hash of the (T + entry), and then sends a second transaction with the entry and linkable ring signature

But, this creates a link between the user who posted the commitment and their ring signature. e.g. it creates a whitelist of accepted inputs, but any ring signature which matches the whitelist can be linked back to whomever added the entry to the whitelist?

**Comment by jchen86** [comment]
Apologies for confusion -  unless there's a way to hide sender identity, we would be using two different key pairs for sending transaction and creating a ring signature. So yes, it's possible to link back to the identity that submitted the transaction but it wouldn't be a problem as long as the entry cannot be linked back to the other identity used to create the ring signature. Hopefully this make sense?

**Comment by HarryR** [comment]
I've run into the problem a handful of times so far - who pays for Gas, e.g. if i transfer ETH into another account, then submit the transaction from that account, then it's still linkable - account abstraction would be a good solution for this as it means contracts could pay their own gas upon receipt of a valid transaction.

**Comment by jchen86** [comment]
@HarryR thanks for sharing your experience!

We've create a proof of concept of the above use case using your library:
https://github.com/fernnetwork/fern-anonymous-identity-registry-poc

This PoC will be presented by @makevoid at the [Polkadot London meetup](https://www.meetup.com/Polkadot-London/events/254240112/), where Francesco will talk about how Fern will enable an ecosystem of independent, compliant, yet anonymously engaged, node and oracle providers. 

This issue can now be closed. Thanks again for the great library!
